MODULE PARSRTM

#include "tsmbkind.h"

IMPLICIT NONE

SAVE

!     ------------------------------------------------------------------
!     Parameters relevant to AER's RRTM-SW radiation scheme
!     030224  JJMorcrette
!
!     Modified for g-point reduction from 224 to 112.  
!     Swap code below to restore 224 g-point set. 
!     Mar2004 MJIacono, AER
!     ------------------------------------------------------------------

INTEGER_B, PARAMETER :: JPLON  = 1
INTEGER_B, PARAMETER :: JPLAY  = 203
INTEGER_B, PARAMETER :: JPAER  = 6
INTEGER_B, PARAMETER :: JPSW   = 14

INTEGER_B, PARAMETER :: JPG    = 16
INTEGER_B, PARAMETER :: JPBAND = 29
INTEGER_B, PARAMETER :: JPB1   = 16
INTEGER_B, PARAMETER :: JPB2   = 29
! Use for 112 g-points
INTEGER_B, PARAMETER :: JPGPT  = 112
! Use for 224 g-points
!INTEGER_B, PARAMETER :: JPGPT  = 224

INTEGER_B, PARAMETER :: JMCMU  = 32
INTEGER_B, PARAMETER :: JMUMU  = 32
INTEGER_B, PARAMETER :: JMPHI  = 3
INTEGER_B, PARAMETER :: JMXANG = 4
INTEGER_B, PARAMETER :: JMXSTR = 16

! Use for 112 g-points
INTEGER_B, PARAMETER :: NG16 = 6
INTEGER_B, PARAMETER :: NG17 = 12
INTEGER_B, PARAMETER :: NG18 = 8
INTEGER_B, PARAMETER :: NG19 = 8
INTEGER_B, PARAMETER :: NG20 = 10
INTEGER_B, PARAMETER :: NG21 = 10
INTEGER_B, PARAMETER :: NG22 = 2
INTEGER_B, PARAMETER :: NG23 = 10
INTEGER_B, PARAMETER :: NG24 = 8
INTEGER_B, PARAMETER :: NG25 = 6
INTEGER_B, PARAMETER :: NG26 = 6
INTEGER_B, PARAMETER :: NG27 = 8
INTEGER_B, PARAMETER :: NG28 = 6
INTEGER_B, PARAMETER :: NG29 = 12

! Not currently active
!INTEGER_B, PARAMETER :: NGS16 = 6
!INTEGER_B, PARAMETER :: NGS17 = 18
!INTEGER_B, PARAMETER :: NGS18 = 26
!INTEGER_B, PARAMETER :: NGS19 = 34
!INTEGER_B, PARAMETER :: NGS20 = 44
!INTEGER_B, PARAMETER :: NGS21 = 54
!INTEGER_B, PARAMETER :: NGS22 = 56
!INTEGER_B, PARAMETER :: NGS23 = 66
!INTEGER_B, PARAMETER :: NGS24 = 74
!INTEGER_B, PARAMETER :: NGS25 = 80
!INTEGER_B, PARAMETER :: NGS26 = 86
!INTEGER_B, PARAMETER :: NGS27 = 94
!INTEGER_B, PARAMETER :: NGS28 = 100
!INTEGER_B, PARAMETER :: NGS29 = 112

! Use for 224 g-points
!INTEGER_B, PARAMETER :: NG16 = 16
!INTEGER_B, PARAMETER :: NG17 = 16
!INTEGER_B, PARAMETER :: NG18 = 16
!INTEGER_B, PARAMETER :: NG19 = 16
!INTEGER_B, PARAMETER :: NG20 = 16
!INTEGER_B, PARAMETER :: NG21 = 16
!INTEGER_B, PARAMETER :: NG22 = 16
!INTEGER_B, PARAMETER :: NG23 = 16
!INTEGER_B, PARAMETER :: NG24 = 16
!INTEGER_B, PARAMETER :: NG25 = 16
!INTEGER_B, PARAMETER :: NG26 = 16
!INTEGER_B, PARAMETER :: NG27 = 16
!INTEGER_B, PARAMETER :: NG28 = 16
!INTEGER_B, PARAMETER :: NG29 = 16

!     ------------------------------------------------------------------
END MODULE PARSRTM


