MODULE PARSRTM


#include "tsmbkind.h"

IMPLICIT NONE

SAVE

!     ------------------------------------------------------------------
!     Parameters relevant to AER's RRTM-SW radiation scheme

!     030224  JJMorcrette
!     ------------------------------------------------------------------

INTEGER_M, PARAMETER :: JPLON  = 1
INTEGER_M, PARAMETER :: JPLAY  = 203
INTEGER_M, PARAMETER :: JPAER  = 6
INTEGER_M, PARAMETER :: JPSW   = 14


INTEGER_M, PARAMETER :: JPG    = 16
INTEGER_M, PARAMETER :: JPBAND = 29
INTEGER_M, PARAMETER :: JPB1   = 16
INTEGER_M, PARAMETER :: JPB2   = 29
INTEGER_M, PARAMETER :: JPGPT  = 224

INTEGER_M, PARAMETER :: JMCMU  = 32
INTEGER_M, PARAMETER :: JMUMU  = 32
INTEGER_M, PARAMETER :: JMPHI  = 3
INTEGER_M, PARAMETER :: JMXANG = 4
INTEGER_M, PARAMETER :: JMXSTR = 16

INTEGER_M, PARAMETER :: NG16 = 16
INTEGER_M, PARAMETER :: NG17 = 16
INTEGER_M, PARAMETER :: NG18 = 16
INTEGER_M, PARAMETER :: NG19 = 16
INTEGER_M, PARAMETER :: NG20 = 16
INTEGER_M, PARAMETER :: NG21 = 16
INTEGER_M, PARAMETER :: NG22 = 16
INTEGER_M, PARAMETER :: NG23 = 16
INTEGER_M, PARAMETER :: NG24 = 16
INTEGER_M, PARAMETER :: NG25 = 16
INTEGER_M, PARAMETER :: NG26 = 16
INTEGER_M, PARAMETER :: NG27 = 16
INTEGER_M, PARAMETER :: NG28 = 16
INTEGER_M, PARAMETER :: NG29 = 16

INTEGER_M, PARAMETER :: NGS16 = 0
INTEGER_M, PARAMETER :: NGS17 = 16
INTEGER_M, PARAMETER :: NGS18 = 32
INTEGER_M, PARAMETER :: NGS19 = 48
INTEGER_M, PARAMETER :: NGS20 = 64
INTEGER_M, PARAMETER :: NGS21 = 80
INTEGER_M, PARAMETER :: NGS22 = 96
INTEGER_M, PARAMETER :: NGS23 = 112
INTEGER_M, PARAMETER :: NGS24 = 128
INTEGER_M, PARAMETER :: NGS25 = 144
INTEGER_M, PARAMETER :: NGS26 = 160
INTEGER_M, PARAMETER :: NGS27 = 176
INTEGER_M, PARAMETER :: NGS28 = 192
INTEGER_M, PARAMETER :: NGS29 = 208

!     ------------------------------------------------------------------
END MODULE PARSRTM


